services:
  - type: web
    name: pricealerter-in
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_ENV
        value: production
      - key: HOST_URL
        value: https://pricealerter.in
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
